### PR TITLE
Update doctoc deps

### PR DESCRIPTION
**Pull request by gyroflaw**
Fix https://github.com/ozum/concat-md/issues/29
Since the prior version of doctoc contains some vulnerabilities it needs to be updated.

### CODE REVIEW

**Comment by gyroflaw** [comment]
Hi @ozum , could you please check this PR and merge if it looks good to you?

**Comment by gyroflaw** [comment]
@ozum, thanks for merging this PR, and could you please let me know when the new version with patched deps can be published?

**Comment by ozum** [comment]
@gyroflaw. I published the package to npm.

By the way; In case of an emergency for the version of dependencies, look at [overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) of package.json. I use it for a couple of projects when PRs are not merged rapidly.

It's a temporary solution but usually works well. Thanks for the PR.

**Comment by gyroflaw** [comment]
And could you please let me know there is any specific reason to [remove `package-lock.json`](https://github.com/ozum/concat-md/commit/d55b88c8196aa48fc56911c88c60ba902deb7f0c)?

**Comment by gyroflaw** [comment]
> I usually recreate it from scratch when I bump a dependency version because sometimes (usually in complex dependency graphs) it mixes old and new versions of the packages.

Thanks for the answer 👍

**Pull request merged**
